# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.7"

services:
  aiohttp: &aiohttp
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    ports:
      - "8080:8080"

    command: python server.py

