# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.8"

services:
  django:
    &django
    build:
      context: ../
      dockerfile: deploy/Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - redis

    environment:
      - DEBUG=False
      - REDIS_HOST=redis

    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"