# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.8"

services:
  django:
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    ports:
      - "8000:8000"

    links:
      - db

    environment:
      - DJANGO_DB_HOST=db # without it django does not see postgres

    # cool hook - just wait 5 seconds while psql is loading - without any entrypoint shell scripts!
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py loaddata fixtures.json && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14.2-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=project

volumes:
  postgres_data:
