# local running: docker-compose -f deploy/docker-compose.yml -p ws up --build
version: '3.8'

services:
  web-0: &fast-api
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: [ "/bin/bash", "/app/web_run.sh" ]

    environment:
      - EXPOSE_PORT=8880

  web-1:
    <<: *fast-api
    environment:
      - EXPOSE_PORT=8881


  web-2:
    <<: *fast-api
    environment:
      - EXPOSE_PORT=8882

  nginx:
    build:
      context: ../
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 8400:8400
    depends_on:
      - web-0
      - web-1
      - web-2

  redis:
    image: redis:6.0
