# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.7"

services:
  aiohttp:
    container_name: main_server
    build:
      context: ../
      dockerfile: deploy/Dockerfile

    ports:
      - "8080:8080"

    links:
      - mongo

    environment:
      - MONGO_HOST=mongo # container_name of mongo !

    command: "python main.py"

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"
