# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.8"

services:
  aiohttp:
    container_name: main_server
    build:
      context: ../
      dockerfile: deploy/Dockerfile

    ports:
      - "8080:8080"

    links:
      - mongo_db

    environment:
      - MONGO_HOST=mongo_db

    command: "python main.py"

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
